ORIGIN_TOP_LEFT = 0
ORIGIN_TOP_RIGHT = 1
ORIGIN_BOTTOM_LEFT = 2
ORIGIN_BOTTOM_RIGHT = 3

LED_PIN = 18
LED_DMA = 10
LED_FREQ = 800000
LED_INVERT = False
LED_CHANNEL = 0

CLOCK_WIDTH = 12
CLOCK_HEIGHT = 13
CLOCK_ORIGIN = ORIGIN_TOP_RIGHT